### ISSUE TITLE
xLINK dynamic configuration example

### ISSUE THREAD

**Issue by keithm-xmos** [xmos/xcore_sdk#440]
Add an example that demonstrates how to dynamically configure xLINKs (5 wire and 2 wire, streaming or not)

Potentially useful reference: https://www.xmos.ai/download/AN01024:-xCONNECT-dynamic-configuration-demo(1.0.0rc4).pdf

**Comment by xmos-jmccarthy** [comment]
Scope:
lib_trycatch added to fwk_core
xlink example in xcore_sdk/examples/freertos featuring 2 build configs, 2L and 5L (pending pinout check)
example will just be a throughput test and require 2 explorer boards 2v0.

Targets:
2L max theoretical throughput is 160Mbit/s
5L max theoretical throughput is 400Mbit/s

**Comment by andrewdewhurst** [comment]
Just wondering about the implications of streaming channels on an RTOS.  I think streaming channels are statically allocated, which consumes the resource forever, but also what happens when the destination process stalls?  There is back-pressure to the sender, but once it backs-up, data is left in a pipeline between sender and receiver.
So, it seems that when a transmitting and receiving task can be interrupted gets complicated!

**Comment by andrewdewhurst** [comment]
Not sure this is relevant, but I thought a normal channel blocked until the receiver side acknowledged it – so in the RTOS world I assume that the sender can’t get de-scheduled until it finishes.
For a streaming channel, then the communication is still blocking but only when the pipeline of stages in the channel all et stalled – i.e. it backs up.  Anyway, I was worrying about issues where you don’t know if the thing you sent was received, or if you could tear down a channel when there is still data in flight.

Anyway – I don’t need you to explain this to me, just worry about it for me!

Andrew
